apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: bitnami/mongodb:6.0.2
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32184